### ISSUE TITLE
Any luck developing with Safari?

### ISSUE THREAD

**Issue by alexblack** [enuchi/React-Google-Apps-Script#94] opened 2021-05-26 00:47 UTC
Thanks for this library - we're having success using it to build an addon with React.  While our addon works in Chrome in development, it doesn't start up in Safari in development (it does work in production though).

I get:

`serverFunctions.myFunctionNameHere is not a function.`

**Comment by enuchi** [comment] 2021-05-27 04:47
Hey @alexblack, thanks for pointing this out. Looks like it's an issue with [gas-client](github.com/enuchi/gas-client), which is what I built to support local development. Think I've identified what the issue is so hope to patch soon! Will post again here when I fix.

**Comment by alexblack** [comment] 2021-05-27 04:50
Fantastic!

**Comment by enuchi** [comment] 2021-05-29 05:40
Hi @alexblack, can you run `npm install gas-client@latest` in your project and see if it works in Safari in development?

**Comment by alexblack** [comment] 2021-05-29 15:45
> Hi @alexblack, can you run `npm install gas-client@latest` in your project and see if it works in Safari in development?

Yes, amazing, I can confirm it works in Safari.  Thanks again!!

**Comment by enuchi** [comment] 2021-05-29 18:08
Fixed by #97 and https://github.com/enuchi/gas-client/pull/14

**Closed by enuchi** 2021-05-29 18:08 UTC
